/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:294b50b4-cee2-4432-81e9-4f953c7fd229",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_nV8Jioz4g",
    "aws_user_pools_web_client_id": "6nkbv2vggpchdbketqcd3v7l4d",
    "oauth": {}
};


export default awsmobile;
